excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://healthyman.github.io
title: Onlylondon Properties
tagline: Londons leading property website. Find a home to Buy or Rent in London from Trusted Estate Agents.
description: Londons leading property website. Find a home to Buy or Rent in London from Trusted Estate Agents.
paginate: 5